# Generated by Django 2.2.2 on 2019-06-25 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('targetAmount', models.FloatField()),
                ('currentAmount', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('topic', models.IntegerField(choices=[(1, 'Science'), (2, 'IT'), (3, 'Entertainment'), (4, 'Other')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('telNumber', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'WAITING'), (2, 'PAID'), (3, 'REJECTED'), (4, 'EXPIRED')])),
                ('payment_type', models.IntegerField(choices=[(1, 'QIWI'), (2, 'YANDEX'), (3, 'RFI')])),
                ('expirationTime', models.DateTimeField()),
                ('siteId', models.TextField()),
                ('billId', models.TextField()),
                ('id_projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='api.User'),
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=150)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
