# Generated by Django 2.2.2 on 2019-06-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('targetAmount', models.BigIntegerField()),
                ('currentAmount', models.BigIntegerField()),
                ('description', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('topic', models.IntegerField(choices=[(1, 'Science'), (2, 'IT'), (3, 'Entertainment'), (4, 'Other')])),
                ('tags', models.TextField()),
                ('date', models.DateTimeField()),
                ('telNumber', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.BigIntegerField()),
                ('status', models.TextField()),
                ('expirationTime', models.CharField(max_length=120)),
                ('siteId', models.TextField()),
                ('billId', models.TextField()),
                ('id_projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
