# Generated by Django 2.2.2 on 2019-06-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'QIWI'), (2, 'YANDEX'), (3, 'RFI')], default=1),
            preserve_default=False,
        ),
    ]
