# Generated by Django 2.2.2 on 2019-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default='2019-06-26T18:33:07.132852+00:00'),
        ),
        migrations.AlterField(
            model_name='project',
            name='telNumber',
            field=models.CharField(max_length=12),
        ),
    ]
