# Generated by Django 2.2.2 on 2019-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190621_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currentAmount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='targetAmount',
            field=models.FloatField(),
        ),
    ]
